<?php

/**
 * @file
 * User Encrypt hooks implementation.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info_alter().
 */
function user_encrypt_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'user') {
    $fields['name']->getItemDefinition()->setClass('\Drupal\user_encrypt\UserEncryptNameItem');
  }
}
