user_encrypt.settings:
  type: config_object
  label: 'User Encrypt Settings'
  mapping:
    user_encrypt:
      type: boolean
      label: 'Encrypt all user data.'
    encrypt_profile:
      type: string
      label: 'Encryption profile to use.'
